= Asciidoctor: New, Noteworthy, and Beyond
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
:experimental:
:repository-name: presentation-asciidoctor-new-noteworthy-beyond
:branch: devoxx-2017
:uri-bespoke: http://markdalgleish.com/projects/bespoke.js
:uri-bundler: http://bundler.io
:uri-gulp: https://gulpjs.com
:uri-node: https://nodejs.org
:uri-nvm: https://github.com/creationix/nvm
:uri-ruby: https://www.ruby-lang.org
:uri-rvm: https://rvm.io
:uri-yarn: https://yarnpkg.com

[abstract]
--
Event page: https://cfp.devoxx.be/2017/talk/TWI-5560/Asciidoctor:_New,_Noteworthy,_and_Beyond[Devoxx 2017]

Presented by: https://github.com/lordofthejars[Alex Soto]

// tag:abstract[]
Asciidoctor continues to take technical documentation by storm, especially in the Java sector.
From software projects like Spring, JUnit, Hiberate, and Elastic, to specifications like CDI and Bean Validation, to tech publishers like InfoQ, O'Reilly, and independents, you don't have to look far to find AsciiDoc powering documentation.
These abundant and diverse use cases have helped push Asciidoctor to new limits.
So what's new and where's it headed?

I'll start by covering the core mission of Asciidoctor and what changes we're trying to push for in documentation.
Then, I'll survey recent improvements that have been introduced into the language and core processor.
I'll then present some of the extensions, integrations, and tools that have been developed around core.
I'll talk about how the processor fits with other components, such as static site generators, and what other software tools and processes are still needed.
Finally, I'll discuss where we're headed with the AsciiDoc language and ecosystem.

If you're using the AsciiDoc writing format or are interested in learning more about it, this talk will give you lots of information to take back to your writing desk.
// end:abstract[]
--

== View online

https://opendevise.github.io/{repository-name}/at/{branch}[Slides]
&middot;
https://www.youtube.com/watch?v=T7RVT2_ntRU[Video]
&middot;
https://github.com/opendevise/{repository-name}/blob/{branch}/src/notes/script.adoc[Script]

== View slides locally

First, ensure you have the following installed:

. {uri-node}[Node.js] >= 4.2 footnote:[You're strongly encouraged to use {uri-nvm}[nvm] to manage Node.]
. {uri-yarn}[Yarn]

 $ npm install -g yarn

. {uri-gulp}[Gulp] (command line interface only)

 $ npm install -g gulp-cli

. {uri-ruby}[Ruby >= 2] footnote:[You're strongly encouraged to use {uri-rvm}[RVM] to manage Ruby.]

 $ rvm use 2.4.2 --install

. {uri-bundler}[Bundler]

 $ gem install bundler

Next, install dependencies (if you ran the generator with the `--skip-install` switch):

 $ yarn
   bundle --path=.bundle/gems

Finally, build and serve the presentation!

 $ gulp serve

You can view the presentation in your browser at the URL displayed in the console.
Use the kbd:[<-] and kbd:[->] arrows to navigate the slides.
You can use kbd:[<space>] and kbd:[Shift+<space>] to navigate as well.
Most presentation clickers are compatible with these key bindings.

To build the presentation without starting the preview server, use:

 $ gulp

In either case, the files are built into the [.path]_dist_ directory.
You can view the slides outside of the local preview server by navigating to [.path]_dist/index.html_ in your browser.

== kbd:[o] -- Slide Overview Mode

This presentation comes with a built-in slide overview mode.
To activate it, simply visit the presentation in your browser and press kbd:[o].
The slides will be rearranged in a grid that you can scroll or navigate with the keyboard.
Press enter to select the highlighted slide and return to presentation mode.

== kbd:[F11] -- Full Screen Mode

This presentation will automatically scale to fit an entire 16:9 screen.
Simply activate full screen mode in your browser by pressing kbd:[F11].

== Using the Presentation Console

This presentation can be broadcast and controlled using ensuite-present.
ensuite-present is a local web app that provides a presentation console.
Once install, you launch it using the `enprez` command.

=== Overview

The presentation console consists of two browser windows.
One is for the presentation console the speaker sees.
This view consists of the current slide, the next slide, and speaker notes.
The speaker notes in the console are taken from the sidebar block in each slide that has the role `cue`.
The other view is the one that goes on the projector screen for the audience to see.

=== Installation

To use ensuite-present, you first need to install the node module using:

 $ npm install -g ensuite-present

=== Launch

Then, open a new terminal and launch the application, which is named `enprez`.

 $ enprez

NOTE: You don't need to have a running presentation when you launch the application.
It's a web app, so it loads the presentation when you load the URL of the console in your browser.

In a separate terminal, run the presentation, as described above:

 $ gulp serve

Finally, load the presentation into the console by visiting the following URL.

 http://localhost:4320/pages/console/?slide-deck-url=http://localhost:8000/?ensuite

You're looking at the speaker view.
You can use this view to practice your presentation.

When you're ready to present, you need to load the window the presentation console will control that gets shown to the audience.

 http://localhost:4320/pages/viewer/

After loading that window, refresh the speaker window (press kbd:[F5]).
Now move the viewer window to the projected monitor for the audience to see.

=== Review

To review, you run ensuite-present using:

 $ enprez

Then you run the presentation in a separate terminal:

 $ gulp serve

Finally, you open two browser windows and navigate to the following two URLs:

Projector view::
http://localhost:4320/pages/viewer/

Presenter console::
http://localhost:4320/pages/console/?slide-deck-url=http://localhost:8000/?ensuite

When broadcasting the presentation, you need to load the viewer first.
It will be blank to start as it's waiting for slide data.
Load the console view and the first slide will be sent to the viewer.
At this point, you're ready to present.
Good luck!

== Customizing the Port

By default, the preview server runs on port 8000.
To change this default, you can assign a different number to the PORT environment variable:

 $ PORT=8888 gulp serve

== Publish to GitHub Pages

The Gulp build includes a task to publish the presentation to GitHub Pages.

First, make sure you have initialized the project as a git repository and linked it to a GitHub project.
The task assumes that the git remote named `origin` points to the repository on GitHub.

Now you can build the presentation and publish it to GitHub Pages using:

 $ gulp publish

The files in the [.path]_dist_ directory end up in the `gh-pages` branch in the repository on GitHub.
From there, they can be viewed in a browser from anywhere on the web.
