//.TODO
// - add narrative for Bespoke
// - upstream builds (fun takeaway)
= Asciidoctor: New, Noteworthy, & Beyond
:icons: font

Hello everyone!
//My name is Dan Allen and I'm the lead of the Asciidoctor project.
My name is Alex Soto and I'm the creator of AsciidoctorJ, the Java API for Asciidoctor.
In the brief time we have together, I'm going to cover what's new, noteworthy, and beyond in the Asciidoctor ecosystem.

Specifically, I'm going to talk about:

* Why we do what we do
* A little surprise
//^ this surprise is the logo
* New language and processor features
* The growth of the ecosystem
* Where Asciidoctor is headed
* And finally, a big surprise.
//^ this surprise is Antora

I'll set the stage by reminding you what Asciidoctor is all about.
//To get started, I'll restate what Asciidoctor is all about.

== Mission

Asciidoctor is a toolchain for parsing and converting AsciiDoc documents so they can be published in a variety of formats, like an HTML site, a PDF document, and even these slides.

So what motivates us to take on this challenge?
This tweet sums it up.

"The more I work with @asciidoctor, the more I love writing documentation.
Very nice when the default output is gorgeous."
-- Garrett D’Amore

That's it right there.
We want writers to love writing documentation and be productive at doing it.
And we want readers to love reading documentation and be able to learn effectively from it.

Now, speaking of gorgeous, time for the first surprise.

== Logo

The second oldest open issue in the Asciidoctor repository is the issue to design a logo.
Having upwards of 250 comments, it's literally bursting at the seams.
After numerous ideas, directions, and discussions, it's time to finally bring this thing to a close.
So I'm proud to announce Asciidoctor's new logo, which was rendered by Marián Hlaváč.

(raise the curtain)

The A, obviously, is for Asciidoctor and AsciiDoc.
The equals sign is the first character that appears in most AsciiDoc documents, designating a doctitle.
Combine those two and you've got the logo.

////
Asciidoctor = productivity.
Asciidoctor = performance.
Asciidoctor = adaptability.
// see https://github.com/asciidoctor/brand/issues/4
////

And with that, we're closing the issue.
Further initiatives involving brand will happen in the brand repository, where you can find the logo files.

Now let's talk about functionality.

== Processor Improvements

As we dive into this section, it's important to know that Asciidoctor is the leading implementation of AsciiDoc and the official home of the AsciiDoc language.
Nothing I'm talking about here is special for Asciidoctor.
This is just AsciiDoc, evolved.

=== xrefstyle

It's now possible to customize the text of a reference using the xrefstyle attribute.
In addition to the default behavior (xrefstyle=basic), you can now use formal notation (xrefstyle=full) or abbreviated notation (xrefstyle=short).
Implementing this feature meant we had to start storing the node being referenced.
That also means this information is now available to extensions.

=== Translations

Thanks to the community, the built-in text label attributes are now translated into 28 languages.
These files are found in the data/locale directory.
Here's an excerpt of the French translation so you can see how the attributes are defined.
To import the translations, just include this file into your document using the include directive.

=== Advanced tag filtering

Asciidoctor has always had the ability to include tagged lines from a file.
Now, it can also exclude them.

Let's assume we have the following Java class.
We can exclude the lines tagged "named" using the negated asterisk.
We could also just identify the excluded tag by name.
You can include all lines, tagged or otherwise (but not the tag markers), using double asterisk.
There are some additional permutations I'm not mentioning here.

=== Stronger SVG support

Asciidoctor now has much better support for SVGs
There are three ways to include an SVG in an HTML document.

* The img element
* The object element
* The embedded svg element

Asciidoctor now supports all three.

By default, Asciidoctor will use the img element.
If you set the interactive option, Asciidoctor will use the object element instead.
If you set the inline option, Asciidoctor will embed the SVG directly into the document.

Much of the driving force for the improvements to SVG support came from Asciidoctor Diagram.

=== Diagrams in SVG

Diagrams are best rendered in SVG.
The new capability of Asciidoctor allows Asciidoctor Diagram to generate diagrams in SVG.
This makes way for interactive diagrams and tighter integration with CSS to style them.
Best of all, a diagram in SVG is super crisp, as you can in this SVG generated by plantuml.
Asciidoctor Diagram integrates with tons diagramming tools, so if you're creating diagrams, it's definitely work a look.

// DJA: we may cut compliance and stability
=== Compliance and stability

As the saying goes, with enough eyes, all bugs are shallow.
Asciidoctor certainly enjoys this benefit.

Users have helped us find all sorts of edge cases, many of which we've fixed straightaway.
120 issues were fixed in the 1.5.6 release alone.
At this point, we're very comfortable saying Asciidoctor is enterprise ready.

We also continue to refine the AsciiDoc language.
The goal is to give you as much capability in as few characters as possible.

=== Asciidoctor Bespoke

Used to create this presentation.
Demonstrates how you can use metadata to produce vastly different outputs.

== Performance

If we're going to talk about performance, we have to address the elephant in the room...

=== "`Why Ruby?`"

In 2012, some people at GitHub started working on an OSS implementation of AsciiDoc in Ruby.
They needed to replace the Python implementation, then a decade old, because it was too slow and insecure.
At the same time, Dan Allen was looking for an AsciiDoc implementation to work with the static site generator he was using.
And so it began.

The challenge was to develop enough of the parser and HTML converter to be deployed on GitHub before they pulled the plug on AsciiDoc.py.
Just the important stuff: paragraphs, section titles, lists, etc.
In other words, a minimum viable product.
After a string of late nights, the initial team managed to pull it off.
In January 2013, Asciidoctor was running on GitHub.com and available to all 5 million+ repositories.
GitHub keeps up with Asciidoctor releases and, overall, the AsciiDoc rendering there is pretty nice.
Asciidoctor also brought AsciiDoc support to many static site generators, including Jekyll and Middleman.

So Asciidoctor is written in Ruby because a) it was a requirement of GitHub.com and b) Dan needed it to work with the Ruby-based static site generator he was using.
As it turns out, Ruby ended up being a huge benefit in terms of portability, as I'll highlight shortly.

=== Isn't Ruby kind of slow?

We recognize Ruby is not the fastest language out there.
But our goal has been to make Asciidoctor as fast as possible regardless.
You could call it an obsession.
We've used every trick in the book to squeeze performance out of Ruby, and it has paid off.

Asciidoctor 1.5.6 is 35% faster than 1.5.5.
In total, that makes Asciidoctor 100 times as fast as AsciiDoc.py.

One trick we use is to only run regular expressions or other expensive matchers on a string if it's even possible a match will occur.
Another trick is to simply upgrade Ruby, as the language itself has enjoyed a lot of performance gains.
We still have some other tricks up our sleeve, but it's less of a priority now that's we've achieved this level of performance.

So why the focus on performance?
Asciidoctor must process a ton of documents, and that can have a significant impact on the turnaround time of CI and CD.
Nobody wants to wait a long time to see results.
Dan recently worked with a project that required over 5,000 AsciiDoc files to be processed in a single build.
While it would take AsciiDoc Python an entire work day to build it, Asciidoctor is able to do it in under 5 minutes.
As you can see, performance has a real impact on workflows in the real world.

Also, the faster Asciidoctor runs, the sooner writers can see a preview of the document in a local editor.
In fact, optimal performance of the processor is incredibly important to the diverse integration and extension ecosystem that depends on core.
So you can be sure we check every commit going into master to ensure it doesn't degrade performance.

////
She's not the fastest pony in the race.
But she's smart and nimble.
The language has made significant improvements over the last few years.
Despite those gains, a program usually performs poorly because of how its developers wrote it--not the language they used.

That's why nothing gets merged into core until I've verified that it does not degrade performance.
I've used all kinds of tricks to squeeze performance out of Ruby.
One trick we use is to only run a regular expression or other expensive matcher if it's even possible that a match will occur.
I also generally avoid dependencies because I want maximum control over performance.

I'm obsessed with core's performance.
That's because it can have a significant impact on CI and CD.
Asciidoctor is going to be asked to process a ton of documents, and nobody wants to wait a long time for that to happen.
As part of my day job, I implement Asciidoctor-based documentation pipelines for enterprises.
One of my recent projects required over 5,000 AsciiDoc files to be processed in a single build.
A build that is triggered multiple times an hour due to the number of people continually updating the company's documentation.
Also, the faster Asciidoctor runs, the quicker writers see a preview of the document.

The numbers:

* Asciidoctor 1.5.6 is 25% faster than 1.5.5.
* And nearly 30% faster than 1.5.0.
* That makes Asciidoctor 100x faster than AsciiDoc.py.

//I still have some tricks up my sleeve for how to make the performance better, but it’s going to get less of a priority now that we’ve achieved the level of performance we have now.

Optimal performance is also incredibly important to the diverse integration and extension ecosystem that depends on core.
////

//TODO Rewrite me and simplify!
//== Integrations & Extensions
== Ecosystem Growth

Asciidoctor has grown beyond anything we could have imagined.

//* 3 language platforms / implementations

* 2.5m gem downloads
* .5m downloads of AsciidoctorJ per year
* 35.5k downloads of Asciidoctor.js
* 70 repositories
* 376 contributors
* 80 supporters

A lot of this growth comes from Asciidoctor reaching new communities.
You see, documentation and technical writing aren't tied to any one platform.
That's why it's crucial that Asciidoctor be able to run in a lot of places.
While core is written in Ruby, there are two bridge technologies that carry core off Ruby island.

* AsciidoctorJ
* Asciidoctor.js

The 70 repositories are really divided amoung these three core providers.
Fortunately, there's no risk of divergence though as they are all based on the same core Ruby code.
And all improvements to the AsciidoctorJ and Asciidoctor.js APIs only strengthen and harden the API in core.

I want to talk about what's new in these bridge implementations and how that progress relates to core.

=== AsciidoctorJ
// SAW: AsciidoctorJ wheel and spoke SVG diagram pending

AsciidoctorJ brings Asciidoctor to the JVM.
It's a pure Java API that manages JRuby underneath and wraps the Ruby API so you can use the Asciidoctor gem without giving it any thought.

//AsciidoctorJ was founded by Alex Soto, who came up with initial concept and wrote the first implementation.
I founded AsciidoctorJ.
I saw what Jason Porter and Andres Almiray were doing to integrate Asciidoctor into Maven and Gradle using JRuby, and I extracted those prototypes into a dedicated project and proper API.
Robert Panzer, who now leads AsciidoctorJ, then came along and really enhanced the implementation.

AsciidoctorJ powers the Maven plugin, the Gradle plugin, the Ant plugin, the JavaDoc Doclet, the IntelliJ plugin, and the Leanpub converter.
While the Maven and Gradle plugins started out using JRuby directly, they have since switched to using AsciidoctorJ.
The Leanpub converter is notable as it's the first converter written using AsciidoctorJ.

So what's else is new?

* thanks to Robert's strong grasp of JRuby, objects now move much more seamlessly between the Ruby and Java runtimes
* this has the impact of making the API feel a lot more Java-like
* it also enables you to be able to write full extensions purely in Java or Groovy, including a Groovy DSL that resembles the native one in Ruby
* consider this example of an inline macro extension written in Ruby to expand an issue reference
* here's the equivalent extension using the Groovy DSL.
* if you're writing extensions, you should definitely be using the 1.6.0 releases, which is where most of these improvements live
* in general, AsciidoctorJ's API is really maturing and filling out, allowing access to more of the Asciidoctor API, some cases even going beyond it in the case of lists and tables.

What's next?

* support for Java 9 is coming; we're waiting on Java 9 support in JRuby, which is happening
* 1.6.0 is in progress; it's really just waiting on the 1.6.0 release of Asciidoctor, which we're going to talk about shortly.

=== Asciidoctor.js

At the same time AsciidoctorJ was getting started, there was this whole other initiative going on to bring Asciidoctor to JavaScript.
That project became Asciidoctor.js and is now led by Guillaume Grosstie.
Asciidoctor.js provides a pure JavaScript implementation of Asciidoctor, which lets you use Asciidoctor in Node, Electron, Nashhorn, and web browsers.
Asciidoctor.js is made by transpiling the Ruby code to JavaScript using Opal.
It seemed like a longshot at first, but Guillaume really worked some magic to make it come together.

Asciidoctor.js is particularly important because it sits at the center of the tooling ecosystem.
In particular, it provides in-application previews of the document, rendered directly in the browser, which is seen in the Atom plugin, the Brackets plugin, the Chrome/Firefox/Opera extension, docgist, and AsciidocFX.
It's also used in several Node-based static site generators.
More on that later.

Here's what's new:

* Asciidoctor.js is now on par with core; there is no reduction in functionality
* The latest release brings full Unicode support, which was a critical step in matching the capability of core
* It also offers a porcelain API (core & extension), which abstracts away method signatures left behind by Opal
* In fact, Asciidoctor.js provides full access to core and its extension points, so you can write extensions in JavaScript.
* Remember that extension you saw in the last section?
* Here's the same extension written for the lastest Asciidoctor.js release.
* You also have the option of simply tranpiling the Ruby extension using Opal.
* Another exciting new feature is support for Slim templates for customizing the output.
 ** This capability brings the Reveal.js converter to JavaScript (and eventually Bespoke)
* Also in the JavaScript world, but not related directly to Asciidoctor.js, there is now a full AsciiDoc language grammar for Atom, which was created by Ludovic Fernandez, Anton Moiseev, and Nico Rikken.
This is by far the best syntax highlighting for AsciiDoc available as it's based on the match expressions in core.
Ludovic also introduced CD practices into Asciidoctor.

Future:

* Performance optimizations to improve tooling and browser preview speeds.
* More API improvements
* Better tooling to compile extensions and templates.
* Figure out how to enable access to more extensions like Asciidoctor Diagram.

== Adoption
// see http://bestgems.org/gems/asciidoctor

Adoption continues to grow like crazy.
We've established that you can use Asciidoctor from Ruby, JavaScript, Java or any language that runs on the JVM.
And many people do use all of those.

That means, year after year, Asciidoctor picks up notable users.
This year has been different.

* In August, Fedora announced it was switching from DocBook to Asciidoctor.
That initiative was sparked in part by a talk Dan gave about Asciidoctor at the Fedora User and Developer conference more than 4 years ago.
* In fact, you can find Asciidoctor used all across Red Hat.
There are personal reasons why this is particularly meaningful to Dan.
* The Java EE leadership recently announced that the Java EE tutorial has been rewritten in AsciiDoc and processed by Asciidoctor.
(ref: https://javaee.github.io/tutorial/)
* Vogella does all its tutorials and trainings in Asciidoctor.
* The Khronos Group uses Asciidoctor for its Vulkan manual.
* Vogella and The Khronos Group are notable for provide funding for the project, as do many of the core contributors.
//* Vaadin
* Matt Raible, who needs no introduction, wrote the JHipster MiniBook in AsciiDoc and converted to PDF for download and print using Asciidoctor PDF.
* Thorben Janssen, author of the thoughts-on-java blog, wrote his Hiberate Tips book in AsciiDoc and converted it to an ebook for self-publishing using Asciidoctor EPUB3.

//To find more users, search for "Who's Using Asciidoctor?"
//Right now it leads to an open issue, but eventually that will become a page on (the new) Asciidoctor site.
There are too many users to mention here.
If you search, you'll quickly be able to find many more.

== The Future

=== Semantic versioning
//=== Release planning
//message: enterprise ready

This is a short section.
Our experience in the past few years, especially as the Asciidoctor ecosystem grows, has made it painfully obvious that we need to shift to semantic versioning.
The time between releases is too long and each micro release of Asciidoctor core is like a major release, so there's no room for anything else.
We need to make room.
We also need to move away from a single version scheme across the ecosystem.
We'll be much better off if projects themselves are versioned semantically and we then track compatible versions.

//Once we shift to 1.6.0, releases will go 1.6.0, 1.7.0, then perhaps 2.0.0 if a major change is ready to go in.
//We may still align the minor version number for the core components, AsciidoctorJ and Asciidoctor.js.
//But the alignment wouldn't extend much outside of those projects.

A shift to semantic versioning should also allow us to release faster.
The minor stuff can go through without getting held up by the major stuff.
//I'm not ready to commit to timed releases yet, but I am thinking about them.

=== Semantic HTML

The initial goal of Asciidoctor was to serve as a drop-in replacement for AsciiDoc.py.
Therefore, we decided to mirror the HTML it produced, as eccentric as it was.
But we always knew we'd eventually need switch to producing HTML that is more semantic and easier to style with CSS.
That time is upon us.

In fact, that transition is already underway.
When we made the HTML for the EPUB3 converter, we experimented with how AsciiDoc mapped to a semantic HTML structure.
We also did the same for the Bespoke converter.
Inspired by that work, Jakub Jirutka has put together a template-based converter named html5s that produces semantic HTML5 output.
You can use all of those today.
The final step is to fold all this work into core and make it the default converter.

////
(slide: html5 logo?)
From the very first day I worked on the HTML output in Asciidoctor I knew there would come a time when we needed to rework the converter to produce semantic HTML.
At the time, I decided to mimic the output of Asciidoc.py, as eccentric as it was, because the goal at that time was to be a drop in replacement and gain adoption.
Well, that's behind us, so it's time to reevaluate.

(slide: html5s converter)
Jakub has started work on a semantic HTML5 converter using custom templates.
I think this is a great way to experiment with the HTML structure so we can get it right.
The EPUB3 and Bespoke converters also propose a lot of ideas for how to better structure the HTML.

Eventually, we want to pull this work into core and replace the existing converter.
Technically, it's not hard to do.
It's just generating different tags than the ones we generate today.
The hard part is deciding on what those tags should be.
We definitely need your input on this.
If you've ever complained about the HTML that Asciidoctor generates, you have a vested interest in giving feedback now so we can get to something that you (as a collective) will like.
We'll also need a new default stylesheet, which is a good time to revisit the aging build process we use to make it now.
////

=== Validation & Grammar
// validaton is part present / new, part future

Another feature users often ask about is validation.
We had always planned on adding validation of AsciiDoc to the processor.
When Dan started working on it in a recent contract, he realized that validation doesn't belong in the processor.
The needs of the processor are just very different from the needs of a validator.
A validator needs to keep track of where every character is in the original source so it can give exact details, offsets, and perhaps even to fix the problem.
The processor only cares about the effective value and general information about context for reporting.
So we needed a validation system.

This is where textlint comes in.
textlint builds on the popularity of eslint.
First, you implement a parser for the language, which we've started to do.
The parser currently only handles blocks, but we're going to (finally) take a crack at parsing inline nodes like formatted text and macros.

What we're hoping will come out of this effort is a strategy for making an inline parser for core, which has long been its Achilles heal.
The regular expression-base approach has brought us a long way, but we're reaching its limits and it's time to get formal.

Once the document is parsed, then you write rules that listen for nodes and look for things to validate.
For example, if you wanted to check for insecure URLs, you could listen for all paragraph nodes and only check for URLs in those regions, thus skipping any verbatim blocks.

icon:tv[insecure url rule example]

As you can see, you get exact line number and character offsets in the message.

Once this system is ready, you have much more control over what is validated.
We'll likely provide a core set of rules, but you can also write your own.

////
I had always planned on adding validation of AsciiDoc to the processor.
As I started to think about how to do it, I realized that it doesn't make sense to do it that way.
The needs of the processor are very different from the needs of a validator.
For example, a processor doesn't really need to keep track of where it took things from.
It only cares about the resolved value and some general information about context for reporting.
A validator, on the other hand, is very concerned about where every character is so that it can give exact character offsets and perhaps even fix the problem itself.
A validator also has a very specific way of collecting and reporting problems.
So we can kind of think of the processor as following the happy path whereas the validator wants to stop and examine every detour and oddity.

That brings us to textlint.
(slide: textlint banner)
I did some searching for a validation framework I could build on.
eslint is a very popular tool for validating JavaScript code.
textlint is inspired by eslint.
First, you implement a parser for the language, which I've started to do.
It currently only parses blocks, but I'm going to take a crack at parsing inline nodes as well like formatted text and macros.
What I'm hoping will come out of this effort is a strategy for making an inline parser for core, which has long been it's Achilles heal.
While the regular expression-based approach has taken us a long way, we're reaching the limits of what we can do with it and it's time to start hammering away at a proper inline grammar.
(slide: github project for textlint-plugin-asciidoc)
Once the document is parsed, then you write rules that listen for nodes and look for things to validate.
For example, if you wanted to check for insecure URLs, you could listen for all paragraph nodes and only check for URLs in those regions, thus skipping any verbatim blocks.
(slide: insecure url rule example)
And you get exact line number and character offsets in the message.

With this system, you have much more control over what is validated.
We'll likely provide a core set of rules, but you can write your own.

We still have a ways to go on the validator, but the good news is that the effort is now underway.
////

=== Antora

I'm very excited to to talk about a new project I've been working on that will impact the future of Asciidoctor: Antora.
//What I'm most excited to cover in this talk, and the most noteworthy, and most likely to impact the future of Asciidoctor, is a new project I've been working on named Antora.
Over the last couple of years, my company has been consulting with other companies on their documentation systems.
What we've noticed is that although there are a ton of static site generators available, few, if any, are well-suited for documentation sites...and more specifically AsciiDoc-based documentation sites.
Antora is designed exactly for that use case.

Antora is an open source, modular Asciidoctor documentation toolchain and workflow that empowers technical writing teams to create, manage, collaborate on, remix, and publish documentation sites sourced from a variety of versioned content repositories without needing expertise in web technologies, build automation, or system administration.

Let's break that down:

* open source - MPL, hosted on GitLab
* modular - each part of Antora is its own package, which means you can modify it to suit your needs; even the UI is a separate component
* versioned content repositories - unlike most static site generators, Antora does not assume that the content is all in one place; instead, it goes out and clones content repositories and plucks files from branches of those repositories
* Asciidoctor - it then integrates deeply with Asciidoctor to generate the pages and the navigation
* without needing expertise - although what Antora does is complex, it's all driven by a simple configuration file called a playbook; this file describes at a high level what needs to be done; where's the source, where's the output, what settings should be used

//Out of Antora comes a new source-to-source xref system for making references across documentation components.

Our goal with Antora is to make documentation sites easy to create, simple to manage, and fun to work on.
And it provides a real world use case for us to improve Asciidoctor.

Antora uses Asciidoctor.js, so it's going to have a particularly strong impact on that project.
I meant it when I said Asciidoctor.js is ready for prime time.

You can learn more about Antora and follow along with development at https://gitlab.com/antora.
I'm also working on a series of posts that introduce the project and explain the problem we're trying to solve with it.
//I talk a lot about that in my other talk, Applying Engineering Practices to Documentation on Wednesday.
You'll be hearing a lot about it in the coming months.

//=== Antora-ize the Docs
=== Docs Overhaul

The Asciidoctor user manual has received considerable contributions over the past year, especially from Rocky Allen and Andrew Carver.
The manual remains the best place to get accurate and up-to-date information about the AsciiDoc syntax and Asciidoctor capabilities.

While it provides great raw material, it needs to be overhauled.
That's where Antora comes in.
We're going to drink our own beer and use Antora for the Asciidoctor documentation.
Not only will this bring some spring cleaning to the content that's already there, it will also address the problem that asciidoctor.org only really talks about core processor.
There are a few pages here and there about other projects in the ecosystem, but they are mostly isolated and one-pagers.
By using Antora, we can shift the documentation for the projects back to the project repositories and then consume them when the site is built.
It's really the exact case for which Antora was designed, so it's a chance to see it in action.
It will also help us improve Antora by applying it to another real world scenario.

So the future is Asciidoctor + Antora.

//Anyone interested in helping with the writing, please reach out to us.
//Many hands make light work.
//We'd also welcome the input of a designer to help improve the UI for Antora that we use for the site.

////
== Funding

Speaking of time, I need time to work on Asciidoctor.
And time means money.
While I mentioned Asciidoctor has received support from 80 backers, only few of those are steady contributions.
If we're going to take on the challenges we have set before us, we're going to need funding, which converts to time and resources.
The more time I can spend on Asciidoctor, the faster we can move.
My effort is multiplied by the effort of the community, but that only happens when I'm actively driving the ship.
////

== Wrapup

TODO

////
== Performance

If you've heard me talk about Asciidoctor before, you know I'm a bit obsessed with its performance.
Yes, I recognize Ruby is not the fastest language out there (by a long shot).
But that kind of makes it a more exciting challenge.
Asciidoctor is written in Ruby and, short of rewriting it, my goal is to make it as fast as possible.

I've used all kinds of tricks to squeeze performance out of Ruby, which would generally apply to any programming language.
The main trick is to only run a regular expression or other expensive matcher if it's even possible that a match will occur.
In other words, be cheap.
Don't do work you don't have to do.
I call it berserker mode.

So why all this focus on performance (aside from my personal challenge)?
The reality is, Asciidoctor is going to be asked to process a ton of documents, and nobody wants to wait a long time for that to happen.
We worked with a client recently who was converting more than 5,000 documents in a single build.
So these numbers start to add up quickly.
If you had to process 2 million documents, it would take AsciiDoc.py a year while it would only take Asciidoctor 3.5 days.

In more human-scale, the faster Asciidoctor runs, the quicker you get to see a preview of your document.
And that brings us to another point.

// Asciidoctor.js
Most of the tooling for Asciidoctor is powered by Asciidoctor.js, which will get to in a minute.
Asciidoctor.js is generated JavaScript, which incurs a bit of a cost.
The faster core is, the faster that generated JavaScript is, and the faster you see a preview of the document in Atom, Chrome, or Firefox.

I still have some tricks up my sleeve for how to make the performance better, but it's going to get less of a priority now that we've achieved the level of performance we have now.
We may focus those optimizations on making Asciidoctor.js faster, for example.
And one day an implementation of Asciidoctor in a faster language might be in the cards.
Time will tell.

== Adoption

Adoption is growing like crazy.
Year after year, Asciidoctor picks up notable users, and this year is no different.
The major adoption news this year came in August when Fedora announced it was switching from DocBook to Asciidoctor.
This migration was 4 years in the making, an effort which was sparked by a talk I gave about Asciidoctor at the Fedora User and Developer conference.
It's safe to say that Red Hat has embraced Asciidoctor across the board.
There are also personal reasons why this one matters to me.

Perhaps pertinent to more folks in this audience, Oracle and the Java EE leadership announced recently that the Java EE tutorial will be rewritten in AsciiDoc and processed by Asciidoctor.
(ref: https://javaee.github.io/tutorial/)
You'll also find Asciidoctor in use in the Spring projects, both for the documentation and, in the case of Spring REST Docs, as generated output for documenting REST APIs.

In terms of adoption by other businesses, Vogella does all its tutorials and trainings in Asciidoctor and the Khronos Group uses Asciidoctor for its Vulkan manual.
I mention both of those specifically because those companies also provide funding for the project.
If you want to talk to an author who's used Asciidoctor firsthand, find Matt Raible.
He wrote the JHipster MiniBook in AsciiDoc and converted it to PDF for download and print using Asciidoctor PDF.

I'm proud to say there are too many users of Asciidoctor to mention here, notable or not.
But you can find a list online of the ones we know about.
While there's still no page on the asciidoctor.org site that lists notable users of Asciidoctor, we keep track of the list in an open issue titled "`Who's Using Asciidoctor?`".
Our plan is to implement that page soon, which ties into something I'll mention later in the talk.
////

////
// SAW: This section is probably too much
// DJA: I decided to fold it into validation since it's tightly related.

== Grammar

When talking about validation, I mentioned inline parsing.
This is probably the Achilles heal of Asciidoctor.
(slide: parser icon => inline AST tree)
When I first implemented Asciidoctor, I was aiming for compatibility with AsciiDoc.py.
Therefore, I took the same approach of using regular expressions to parse inline nodes.
Since AsciiDoc is only a semi-structured language, this works amazingly well.
But we have reached the limits of that strategy.
It's time (perhaps past time) to switch to an inline parser.
It will likely be a recursive decent parser with some overrides since that's what's used in most Markdown implementations.
I'll probably implement it first in the validator, which provides a safe place to work on it.
Once that's worked out, I'll then bring it in to core.
There may be some migration, but I expect that in most cases, it's only going to get more scenarios right, not less.
////
