//.TODO
// - upstream builds (fun takeaway)
= Asciidoctor: New, Noteworthy, & Beyond

Hello everyone!
My name is Dan Allen and I'm the lead of the Asciidoctor project.
In the brief time we have together, I'm going to cover what's new, noteworthy, and beyond in Asciidoctor.

Specifically, I'm going to talk about:

* Asciidoctor's mission
* A little surprise
* New features of the language and capabilities of the processor
* The growth and reach of the ecosystem
* What's next (in Asciidoctor)
* And finally, another surprise

To get started, I'll restate what Asciidoctor is all about.
//For those who may not be familiar with Asciidoctor, let's revisit its mission.

== Mission

Asciidoctor is a toolchain for parsing and converting AsciiDoc documents and publishing them in a variety of formats.

What motivates us to take on this challenge?
This tweet nails it.

"The more I work with @asciidoctor the more I love writing documentation.
Very nice when the default output is gorgeous."
-- Garrett D`'Amore

We want writers to love writing documentation and be productive at it.
And we want readers to love reading documentation and be able to learn effectively from it.

// SAW: I like "Now, speaking of gorgeous" better - it connects to the tweet and can't get misinterpreted.
//Speaking of gorgeous.
Now, speaking of eye candy.

== Logo

The second oldest open issue in the Asciidoctor repository is the issue to design a logo.
Having upwards of 250 comments, it's bursting at the seams.
After numerous ideas, directions, and discussions, it's time to finally bring this thing to a close.
So I'm proud to announce Asciidoctor's new logo, which was rendered by Marián Hlaváč.

icon:slide[logo reveal]

The A is for Asciidoctor and AsciiDoc.
The equals is the first character that appears in most AsciiDoc documents, which designates the doctitle.
Combine those and you get the logo.

////
Asciidoctor = productivity.
Asciidoctor = performance.
Asciidoctor = adaptability.
// see https://github.com/asciidoctor/brand/issues/4
////

And with that, I'm closing the issue.
Further initiatives involving the brand will happen in the brand repository, where you'll also be able to find the logo.

Now let's talk about functionality.

== Processor Improvements

As we dive into this section, it's important to understand that Asciidoctor is the leading implementation of AsciiDoc and the official home of the AsciiDoc language.
So nothing I'm talking about here is special for Asciidoctor.
This is just AsciiDoc, evolved.

=== xrefstyle

It's now possible to customize the text of a reference using the xrefstyle attribute.
In addition to the default behavior, you can use formal notation or you can use abbreviate notation.
Implementing this feature meant we had to start storing the node being referenced, which also means extensions can access this information.
//reference signifier terminology

=== Translations

The built-in labeling attributes are now translated into 28 languages.
These files can be found in the data/locale directory.
Here's a partial example of the French version of this file so you can see how the attributes are defined.
Just include this file into your document to import the translations.

=== Advanced tag filtering

Asciidoctor has always had the ability to include tagged lines from a file.
Now it's possible to exclude those lines.

Let's assume we have the following Java class.
We can exclude the lines tagged "named" using the negated asterisk.
We could have also identified tag by name.
It's also possible to include all lines, tagged or otherwise (but not the tag markers), using double asterisk.
//Q: should we mention that there are a few other cases not mentioned here?
// SAW: That depends on whether you can just list the things off or if they'd need explanation to be of any use.

=== Stronger SVG support

Asciidoctor now has much better SVG support, including support for interactive (object) and inline SVGs (embedded).
Much of the driving factor for the improvements to SVG support came from Asciidoctor Diagram.

// SAW: This content should be said while on the Stronger SVG support slide unless there is a really compelling reason for another slide
=== Moar Diagrams

Diagrams are best rendered in SVG.
The new capability of Asciidoctor has enabled both interactive diagrams and tighter integration with CSS to style them.

=== Compliance and stability

With enough eyes, all bugs are shallow.
That's especially true in Asciidoctor.
Users have helped us find all sorts of edge cases, many of which we have fixed straightaway.
120 issues were fixed in 1.5.6 alone.
At this point, I'm very comfortable saying Asciidoctor is enterprise ready.

We also continue to refine the AsciiDoc language.
The goal is to give you as much capability in as few characters as possible.
//efficiently encoded information

== Performance

Of course, if we're going to talk about performance, we have to address the elephant in the room...

=== "Why Ruby?" screams everyone who isn't a Ruby dev

In 2012, some people at GitHub started working on an OSS Ruby implementation of AsciiDoc.
They needed to replace the Python implementation of AsciiDoc, which, at that point, was a decade old, because it was too slow and insecure.
At the same time, I was looking for an AsciiDoc implementation to work with the static site generator I was using.
And so it began.

The challenge was to develop enough of the parser and HTML converter to be deployed on GitHub before they pulled the plug on AsciiDoc.py.
Just the important stuff: paragraphs, section titles, lists, etc.
In other words, a minimum viable product.
After a string of late nights, we managed to pull it off.
In January 2013, Asciidoctor was running on GitHub.com and available to all 5 million+ repositories.
GitHub keeps in sync with Asciidoctor releases and, in general, the AsciiDoc rendering there is pretty nice.
// GitHub keeps in sync with Asciidoctor releases and, this is why AsciiDoc files render in repositories.

//Asciidoctor Core runs on GitHub and is used in many static site generators.

So Asciidoctor is written in Ruby because a) it was a requirement of GitHub.com and b) I needed it to work with the Ruby-based static site generator I was using.
Ruby ended up being a huge benefit in terms of portability, as I'll highlight in the next topic.

=== Isn't Ruby kind of slow?

I recognize Ruby is not the fastest language out there.
But my goal has been to make Asciidoctor as fast as possible regardless.
You could call it an obsession.
I've used every trick in the book to squeeze performance out of Ruby, and it has paid off.

Asciidoctor 1.5.6 is 25% as fast as 1.5.5.
In total, that makes Asciidoctor 100x faster than AsciiDoc.py.

One trick is to only run a regular expression or other expensive matcher on a string if it's even possible a match will occur.
Another trick is to upgrade Ruby, as the language itself has enjoyed a lot of performance gains.
I still have some tricks up my sleeve, but it's less of a priority now that's we've achieved this level of performance.

Why the focus on performance?
Asciidoctor must process a ton of documents, and that can have a significant impact on the turnaround time of CI and CD.
Plus, nobody wants to wait a long time to see results.
In a recent consulting engagement, we worked with a project that required over 5,000 AsciiDoc files to be processed in a single build.
While it would take AsciiDoc Python 8 hours to build it, Asciidoctor is able to do it in under 5 minutes.
Performance has a real impact on workflows in the real world.

Also, the faster Asciidoctor runs, the sooner writers can see a preview of the document in a local editor.
In fact, optimal performance of the processor is incredibly important to the diverse integration and extension ecosystem that depends on core.
So you can be sure I check every commit going into master to be sure it doesn't degrade performance.

////
She's not the fastest pony in the race.
But she's smart and nimble.
The language has made significant improvements over the last few years.
Despite those gains, a program usually performs poorly because of how its developers wrote it--not the language they used.

That's why nothing gets merged into core until I've verified that it does not degrade performance.
I've used all kinds of tricks to squeeze performance out of Ruby.
One trick we use is to only run a regular expression or other expensive matcher if it's even possible that a match will occur.
I also generally avoid dependencies because I want maximum control over performance.

I'm obsessed with core's performance.
That's because it can have a significant impact on CI and CD.
Asciidoctor is going to be asked to process a ton of documents, and nobody wants to wait a long time for that to happen.
As part of my day job, I implement Asciidoctor-based documentation pipelines for enterprises.
One of my recent projects required over 5,000 AsciiDoc files to be processed in a single build.
A build that is triggered multiple times an hour due to the number of people continually updating the company's documentation.
Also, the faster Asciidoctor runs, the quicker writers see a preview of the document.

The numbers:

* Asciidoctor 1.5.6 is 25% faster than 1.5.5.
* And nearly 30% faster than 1.5.0.
* That makes Asciidoctor 100x faster than AsciiDoc.py.

//I still have some tricks up my sleeve for how to make the performance better, but it’s going to get less of a priority now that we’ve achieved the level of performance we have now.

Optimal performance is also incredibly important to the diverse integration and extension ecosystem that depends on core.
////

//TODO Rewrite me and simplify!
//== Integrations & Extensions
== Ecosystem Growth

Asciidoctor has grown beyond anything we could have imagined.

//* 3 language platforms / implementations

* 2.5M gem downloads
* AsciidoctorJ gets a quarter million downloads a year on Bintray (Gradle)
* AsciidoctorJ maven: about 30,000 a month
* Asciidoctor.js (npm) ?
* 70 repositories
* 376 contributors
* 80 backers

There are in fact three implementations of Asciidoctor:

* Asciidoctor (aka “core”)
* AsciidoctorJ
* Asciidoctor.js

There's no risk of divergence though as they are all based on the same core Ruby code.

So why have all three?
Documentation and technical writing aren't tied to any one platform, so it's important that Asciidoctor be able to run in a lot of places.
In fact, many of the repositories are specific to one or more of these implementations, while others are shared.
I want to talk about what's new in these implementations and how that progress relates to core.

=== AsciidoctorJ
// SAW: AsciidoctorJ wheel and spoke SVG diagram pending

AsciidoctorJ brings Asciidoctor to the JVM.
It's a pure Java API that manages JRuby underneath and wraps the Ruby API so you can use the Asciidoctor gem without even having to think about it.

AsciidoctorJ was founded by Alex Soto, who came up with initial concept and wrote the first implementation.
Credit also goes to Jason Porter and Andres Almiray, who were all simultaneously working on solutions to integrate Asciidoctor into the JVM via JRuby.
Robert Panzer, who now leads AsciidoctorJ, came along and really enhanced the implementation.

So what's new?

* thanks to Robert's strong grasp of JRuby, objects now move much more seamlessly between the Ruby and Java runtimes
* this has the impact of making the API feel a lot more Java-like
* it also enables you to be able to write full extensions purely in Java or Groovy, including a Groovy DSL that resembles the native one in Ruby
* if you're writing extensions, you should definitely be using the 1.6.0 releases, which is where most of these improvements live
* in general, AsciidoctorJ's API is really maturing and filling out, allowing access to more of the Asciidoctor API, and in some cases goes beyond it, including creating and reading lists and tables

AsciidoctorJ powers the Maven plugin, the Gradle plugin, the Ant plugin, the JavaDoc Doclet, and the IntelliJ plugin.
While the Maven and Gradle plugins started out using JRuby directly, they have since switched to using AsciidoctorJ.

What's next?

* 1.6.0 is in progress; it's really just waiting on the 1.6.0 release of Asciidoctor, which we're going to talk about shortly.
* support for Java 9 is coming; we're waiting on Java 9 support in JRuby, which is happening

=== Asciidoctor.js
// SAW: I removed the slide for "Portable extensions", you now need to structure this section out to compliment the example slides for: Inline issue macro (Ruby), Inline issue macro (Javascript), Inline issue macro (Groovy), and Bespoke converter

// SAW: Asciidoctor.js wheel and spoke SVG diagram pending

While AsciidoctorJ was happening, there was this whole other initiative going on to bring Asciidoctor to JavaScript.
That project became Asciidoctor.js and is now led by Guillaume Grosstie.
Asciidoctor.js provides a pure JavaScript implementation of Asciidoctor, which lets you use Asciidoctor in Node, Electron, Nashhorn, and web browsers.
Asciidoctor.js is made by transpiling the Ruby code to JavaScript using Opal.
It seemed like a longshot at first, but Guillaume really worked some magic to make it happen.

Asciidoctor.js is particularly important because it sits at the center of the tooling ecosystem.
In particular, it provides in-application previews of the document, rendered directly in the browser, which is seen in the Atom plugin, the Brackets plugin, the Chrome/Firefox/Opera extension, and docgist.
It's also used in several Node-based static site generators.
More on that later.

Here's what's new:

* Asciidoctor.js is on par with core; there is no reduction in functionality
* it offers a porcelain API (core & extension), which abstracts away artifacts left behind by Opal
* The latest release brings full Unicode support, which was a critical step in matching the capability of core
* Asciidoctor.js provides full access to core and its extension points
* You can write extensions in JavaScript
* It now provides support for templates
 ** This capability brings the Reveal.js and (eventually) Bespoke.js converters to JavaScript.
* Also in the JavaScript world, but not related directly to Asciidoctor.js, there is now a full AsciiDoc language grammar for Atom, which was created by Ludovic Fernandez, Anton Moiseev, and Nico Rikken.
This is by far the best syntax highlighting for AsciiDoc available as it's based on the match expressions in core.

Future:

* Performance optimizations to improve tooling and browser preview speeds.
* More API improvements
* Better tooling to compile extensions and templates.
* Figure out how to enable access to more extensions like Asciidoctor Diagram.

// Q: should we mention other projects?
=== Integration Summary

Improvements to the Asciidoctor.js and AsciidoctorJ APIs are strengthening and hardening the API in core.

== Adoption
// see http://bestgems.org/gems/asciidoctor

We've established that you can use Asciidoctor from Ruby, JavaScript, Java or any language that runs on the JVM.
And many people do use all of those.

Adoption continues to grow like crazy.
Year after year, Asciidoctor picks up notable users, and this year is no different.
There are so many users, in fact, that I simply can't mention them all here.
I'll focus on the notable ones.

* In August, Fedora announced it was switching from DocBook to Asciidoctor.
That migration was 4 years in the making, an effort which was sparked in part by a talk I gave about Asciidoctor at the Fedora User and Developer conference.
There are personal reasons why this one is particularly meaningful for me.
* The Java EE leadership recently announced that the Java EE tutorial has been rewritten in AsciiDoc and processed by Asciidoctor.
(ref: https://javaee.github.io/tutorial/)
* Vogella does all its tutorials and trainings in Asciidoctor.
* The Khronos Group uses Asciidoctor for its Vulkan manual.
* Vogella and The Khronos Group also provide funding for the project.
//* Vaadin
* Matt Raible, who needs no introduction, wrote the JHipster MiniBook in AsciiDoc and converted to PDF for download and print using Asciidoctor PDF.
* Thorben Janssen, author of the thoughts-on-java blog, wrote his Hiberate Tips book in AsciiDoc and converted it to an ebook for self-publishing using Asciidoctor EPUB3.

//To find more users, search for "Who's Using Asciidoctor?"
//Right now it leads to an open issue, but eventually that will become a page on (the new) Asciidoctor site.
If you search, you'll be able to find many more uses of Asciidoctor.

== The Future

* Project Management
* Semantic HTML
* Validation & Grammar
* Docs Overhaul

=== Project Management: Roadmaps & Releases
//message: enterprise ready

// SAW: roadmap image pending

This is a short section.
Our experience in the past few years, especially as the Asciidoctor ecosystem grows, has it painfully obvious that we need to shift to semantic versioning.
Each micro release of Asciidoctor core is like a major release, so there's no room for anything else.
We need to make room.
We also need to move away from a single version scheme across the ecosystem.
//I thought it was the right way to go, but I was mistaken.
//It's only slowed things down.
We'll be much better off if projects themselves are versioned semantically and we then track compatible versions.

Once we shift to 1.6.0, releases will go 1.6.0, 1.7.0, then perhaps 2.0.0 if a major change is ready to go in.

We may still align the minor version number for the core components, AsciidoctorJ and Asciidoctor.js.
But the alignment wouldn't extend much outside of those projects.

A shift to semantic versioning should also allow us to release faster.
I know I've held up the release because minor stuff got stuck behind major stuff.
//I'm not ready to commit to timed releases yet, but I am thinking about them.

=== Semantic HTML

The initial goal of Asciidoctor was to serve as a drop-in replacement for AsciiDoc.py.
Therefore, we decided to mirror the HTML it produced, as eccentric as it was.
But we always knew we'd eventually switch to producing HTML that is more semantic and easier to style with CSS.
That time is upon us.

In fact, that transition is already underway.
When we made the HTML for the EPUB3 converter, we experimented with how AsciiDoc mapped to a semantic HTML structure.
I also did the same for the Bespoke converter, minus the parts that are slide-specific.
Inspired by that work, Jakub Jirutka has put together a template-based converter named html5s that produces semantic HTML5 output.
You can use all of those today.
The final step is to polish it and integrate it into core, likely as the default converter.

////
(slide: html5 logo?)
From the very first day I worked on the HTML output in Asciidoctor I knew there would come a time when we needed to rework the converter to produce semantic HTML.
At the time, I decided to mimic the output of Asciidoc.py, as eccentric as it was, because the goal at that time was to be a drop in replacement and gain adoption.
Well, that's behind us, so it's time to reevaluate.

(slide: html5s converter)
Jakub has started work on a semantic HTML5 converter using custom templates.
I think this is a great way to experiment with the HTML structure so we can get it right.
The EPUB3 and Bespoke converters also propose a lot of ideas for how to better structure the HTML.

Eventually, we want to pull this work into core and replace the existing converter.
Technically, it's not hard to do.
It's just generating different tags than the ones we generate today.
The hard part is deciding on what those tags should be.
We definitely need your input on this.
If you've ever complained about the HTML that Asciidoctor generates, you have a vested interest in giving feedback now so we can get to something that you (as a collective) will like.
We'll also need a new default stylesheet, which is a good time to revisit the aging build process we use to make it now.
////

=== Validation & Grammar
// validaton is part present / new, part future

Another feature users often ask about is validation.
I had always planned on adding validation of AsciiDoc to the processor.
When I started working on it in a recent contract, I realized that validation doesn't belong in the processor.
The needs of the processor are just very different from the needs of a validator.
A validator needs to keep track of where every character is in the original source so it can give exact details, offsets, and perhaps even fix the problem.
The processor only cares about the effective value and general information about context for reporting.
So we needed a validation system.

This is where textlint comes in.
textlint builds on the popularity of eslint.
First, you implement a parser for the language, which I've started to do.
The parser currently only handles blocks, but I'm going to take a crack at parsing inline nodes like formatted text and macros.
What I'm hoping will come out of this effort is a strategy for making an inline parser for core, which has long been its Achilles heal.
The regular expression-base approach has brought us a long way, but we're reaching its limits and it's time to get formal.
Once the document is parsed, then you write rules that listen for nodes and look for things to validate.
For example, if you wanted to check for insecure URLs, you could listen for all paragraph nodes and only check for URLs in those regions, thus skipping any verbatim blocks.

(slide: insecure url rule example)
As you can see, you get exact line number and character offsets in the message.

Once this system is ready, you have much more control over what is validated.
We'll likely provide a core set of rules, but you can also write your own.

////
I had always planned on adding validation of AsciiDoc to the processor.
As I started to think about how to do it, I realized that it doesn't make sense to do it that way.
The needs of the processor are very different from the needs of a validator.
For example, a processor doesn't really need to keep track of where it took things from.
It only cares about the resolved value and some general information about context for reporting.
A validator, on the other hand, is very concerned about where every character is so that it can give exact character offsets and perhaps even fix the problem itself.
A validator also has a very specific way of collecting and reporting problems.
So we can kind of think of the processor as following the happy path whereas the validator wants to stop and examine every detour and oddity.

That brings us to textlint.
(slide: textlint banner)
I did some searching for a validation framework I could build on.
eslint is a very popular tool for validating JavaScript code.
textlint is inspired by eslint.
First, you implement a parser for the language, which I've started to do.
It currently only parses blocks, but I'm going to take a crack at parsing inline nodes as well like formatted text and macros.
What I'm hoping will come out of this effort is a strategy for making an inline parser for core, which has long been it's Achilles heal.
While the regular expression-based approach has taken us a long way, we're reaching the limits of what we can do with it and it's time to start hammering away at a proper inline grammar.
(slide: github project for textlint-plugin-asciidoc)
Once the document is parsed, then you write rules that listen for nodes and look for things to validate.
For example, if you wanted to check for insecure URLs, you could listen for all paragraph nodes and only check for URLs in those regions, thus skipping any verbatim blocks.
(slide: insecure url rule example)
And you get exact line number and character offsets in the message.

With this system, you have much more control over what is validated.
We'll likely provide a core set of rules, but you can write your own.

We still have a ways to go on the validator, but the good news is that the effort is now underway.
////

=== Antora

I'm very excited to to talk about a new project I've been working on that will impact the future of Asciidoctor: Antora.
//What I'm most excited to cover in this talk, and the most noteworthy, and most likely to impact the future of Asciidoctor, is a new project I've been working on named Antora.
Over the last couple of years, my company has been consulting with other companies on their documentation systems.
What we've noticed is that although there are a ton of static site generators available, few, if any, are well-suited for documentation sites...and more specifically AsciiDoc-based documentation sites.
Antora is designed exactly for that use case.

Antora is an open source, modular Asciidoctor documentation toolchain and workflow that empowers technical writing teams to create, manage, collaborate on, remix, and publish documentation sites sourced from a variety of versioned content repositories without needing expertise in web technologies, build automation, or system administration.

Let's break that down:

* open source - MPL, hosted on GitLab
* modular - each part of Antora is its own package, which means you can modify it to suit your needs; even the UI is a separate component
* versioned content repositories - unlike most static site generators, Antora does not assume that the content is all in one place; instead, it goes out and clones content repositories and plucks files from branches of those repositories
* Asciidoctor - it then integrates deeply with Asciidoctor to generate the pages and the navigation
* without needing expertise - although what Antora does is complex, it's all driven by a simple configuration file called a playbook; this file describes at a high level what needs to be done; where's the source, where's the output, what settings should be used

Out of Antora comes a new source-to-source xref system for making references across documentation components.

Our goal with Antora is to make documentation sites easy to create, simple to manage, and fun to work on.
And it provides a real world use case for us to improve Asciidoctor.

Antora uses Asciidoctor.js, so it's going to have a particularly strong impact on that project.
I meant it when I said that Asciidoctor.js was ready for prime time.

You can learn more about Antora and follow along with development at https://gitlab.com/antora.
I'm also working on a series of posts that introduce the project and explain the problem we're trying to solve with it.
I talk a lot about that in my other talk, Applying Engineering Practices to Documentation on Wednesday.
You'll be hearing a lot about it in the coming months.

//=== Antora-ize the Docs
=== Docs Overhaul

The Asciidoctor user manual has received considerable contributions over the past year, especially from Rocky Allen and Andrew Carver.
The manual remains the best place to get accurate and up-to-date information about the AsciiDoc syntax and Asciidoctor capabilities.

While it provides great raw material, it needs to be overhauled.
That's where Antora comes in.
We're going to drink our own beer and use Antora for the Asciidoctor documentation.
Not only will this bring some spring cleaning to the content that is already there, it will also address the problem that asciidoctor.org mostly only covers the core processor.
There are a few pages here and there about other projects in the ecosystem, but they are mostly isolated and one-pagers.
By using Antora, we can shift the documentation for the projects back to the project repositories and then consume them when the site is built.
It's really the exact case for which Antora was designed, so it's a chance to see it in action.
It will also help us improve Antora by applying it to another real world scenario.

Antora + Asciidoctor FTW!

//Anyone interested in helping with the writing, please reach out to us.
//Many hands make light work.
//We'd also welcome the input of a designer to help improve the UI for Antora that we use for the site.

== Funding

Speaking of time, I need time to work on Asciidoctor.
And time means money.
While I mentioned Asciidoctor has received support from 80 backers, only few of those are steady contributions.
If we're going to take on the challenges we have set before us, we're going to need funding, which converts to time and resources.
The more time I can spend on Asciidoctor, the faster we can move.
My effort is multiplied by the effort of the community, but that only happens when I'm actively driving the ship.

== Wrapup

TODO

=== #FIXME# Need to find a place for

// Asciidoctor Diagram
//* speaking of SVGs, tons of new diagramming tools are supported by Asciidoctor Diagram; if you are creating diagrams, it's definitely work a look

// Asciidoctor Bespoke converter
//* Bespoke converter, which created this presentation

// Asciidoctor Reveal.js converter
//* Reveal.js converter, which closely resembles the Bespoke converter; the two influence each other

* Jekyll plugin, the Middleman extension

* Docker container

////
== Performance

If you've heard me talk about Asciidoctor before, you know I'm a bit obsessed with its performance.
Yes, I recognize Ruby is not the fastest language out there (by a long shot).
But that kind of makes it a more exciting challenge.
Asciidoctor is written in Ruby and, short of rewriting it, my goal is to make it as fast as possible.

I've used all kinds of tricks to squeeze performance out of Ruby, which would generally apply to any programming language.
The main trick is to only run a regular expression or other expensive matcher if it's even possible that a match will occur.
In other words, be cheap.
Don't do work you don't have to do.
I call it berserker mode.

So why all this focus on performance (aside from my personal challenge)?
The reality is, Asciidoctor is going to be asked to process a ton of documents, and nobody wants to wait a long time for that to happen.
We worked with a client recently who was converting more than 5,000 documents in a single build.
So these numbers start to add up quickly.
If you had to process 2 million documents, it would take AsciiDoc.py a year while it would only take Asciidoctor 3.5 days.

In more human-scale, the faster Asciidoctor runs, the quicker you get to see a preview of your document.
And that brings us to another point.

// Asciidoctor.js
Most of the tooling for Asciidoctor is powered by Asciidoctor.js, which will get to in a minute.
Asciidoctor.js is generated JavaScript, which incurs a bit of a cost.
The faster core is, the faster that generated JavaScript is, and the faster you see a preview of the document in Atom, Chrome, or Firefox.

I still have some tricks up my sleeve for how to make the performance better, but it's going to get less of a priority now that we've achieved the level of performance we have now.
We may focus those optimizations on making Asciidoctor.js faster, for example.
And one day an implementation of Asciidoctor in a faster language might be in the cards.
Time will tell.

== Adoption

Adoption is growing like crazy.
Year after year, Asciidoctor picks up notable users, and this year is no different.
The major adoption news this year came in August when Fedora announced it was switching from DocBook to Asciidoctor.
This migration was 4 years in the making, an effort which was sparked by a talk I gave about Asciidoctor at the Fedora User and Developer conference.
It's safe to say that Red Hat has embraced Asciidoctor across the board.
There are also personal reasons why this one matters to me.

Perhaps pertinent to more folks in this audience, Oracle and the Java EE leadership announced recently that the Java EE tutorial will be rewritten in AsciiDoc and processed by Asciidoctor.
(ref: https://javaee.github.io/tutorial/)
You'll also find Asciidoctor in use in the Spring projects, both for the documentation and, in the case of Spring REST Docs, as generated output for documenting REST APIs.

In terms of adoption by other businesses, Vogella does all its tutorials and trainings in Asciidoctor and the Khronos Group uses Asciidoctor for its Vulkan manual.
I mention both of those specifically because those companies also provide funding for the project.
If you want to talk to an author who's used Asciidoctor firsthand, find Matt Raible.
He wrote the JHipster MiniBook in AsciiDoc and converted it to PDF for download and print using Asciidoctor PDF.

I'm proud to say there are too many users of Asciidoctor to mention here, notable or not.
But you can find a list online of the ones we know about.
While there's still no page on the asciidoctor.org site that lists notable users of Asciidoctor, we keep track of the list in an open issue titled "`Who's Using Asciidoctor?`".
Our plan is to implement that page soon, which ties into something I'll mention later in the talk.
////

////
// SAW: This section is probably too much
// DJA: I decided to fold it into validation since it's tightly related.

== Grammar

When talking about validation, I mentioned inline parsing.
This is probably the Achilles heal of Asciidoctor.
(slide: parser icon => inline AST tree)
When I first implemented Asciidoctor, I was aiming for compatibility with AsciiDoc.py.
Therefore, I took the same approach of using regular expressions to parse inline nodes.
Since AsciiDoc is only a semi-structured language, this works amazingly well.
But we have reached the limits of that strategy.
It's time (perhaps past time) to switch to an inline parser.
It will likely be a recursive decent parser with some overrides since that's what's used in most Markdown implementations.
I'll probably implement it first in the validator, which provides a safe place to work on it.
Once that's worked out, I'll then bring it in to core.
There may be some migration, but I expect that in most cases, it's only going to get more scenarios right, not less.
////
